### PR TITLE
Show debug

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by kane-c** [comment]
What is this for? Debugging info on ISS queries?

What's the plan for removing this in prod?

**Comment by DanielHeath** [comment]
It's been in for awhile (see the deleted mixin) - we've left it in for prod so far.

**Comment by DanielHeath** [comment]
lots and lots of questions coming my way (of the form 'what query is generated when I choose these options') - need to have a way to let people self service

**Comment by kane-c** [comment]
++

**Pull request merged**
