### PR TITLE
Fix styleguide pages

### PR DESCRIPTION
**Pull request by DanielHeath**
Pull out the fix to its own branch to see if it's the cause of things failing on sauce

### CODE REVIEW

**Comment by danni** [comment]
Looks wrong. Are there missing files?

**Comment by danni** [comment]
We also want the footer on every page.

**Comment by DanielHeath** [comment]
Fixed.

**Comment by DanielHeath** [comment]
Ah - I see what you mean now.

**Comment by DanielHeath** [comment]
I've extracted a separate parent page so that the styleguide doesn't inherit the footer.

**Comment by DanielHeath** [comment]
@danni anything else on this?

**Comment by danni** [comment]
++

**Pull request merged**
