### PR TITLE
Reinstate "Inline the main logo so it doesn't load after the rest of …

### PR DESCRIPTION
**Pull request by DanielHeath**
…the page"

Currently the header appears after the rest of the page has loaded.
This change renders the SVG inline which ensures the logo appears with the text.

This reverts commit 16db07b3024707242fda04cb790e9a4c16205a9c.

### CODE REVIEW

**Comment by danni** [comment]
Is it going to crash Chrome still?

**Comment by danni** [comment]
Also needs the SVG CSS directive to align to the pixel grid. As the sharp edges are anti-aliased on my screen.

**Comment by danni** [comment]
Okay, Chrome works for me now. Maybe it was to do with the sizing/trying to resize it in devtools dynamically. Or maybe I'd run out of memory before I rebooted yesterday.

**Comment by danni** [comment]
One other difference is the Izzy is now higher than the Ask.

**Comment by danni** [comment]
screenshot from 2015-09-14 10-49-00
screenshot from 2015-09-14 10-48-55

**Comment by danni** [comment]
Your other option is to base64 inline it. Which I believe is a thing Webpack can do for you.

**Comment by DanielHeath** [comment]
@isaacwilliams I'll ship this once I get the trimmed version of the logo.

**Comment by DanielHeath** [comment]
++

**Pull request merged**
