### PR TITLE
Added quotation marks to school

### PR DESCRIPTION
**Pull request by robynk**
The search string only works in ISS with the quotation marks.

### CODE REVIEW

**Comment by DanielHeath** [comment]
Does that change something in an important way?

**Comment by DanielHeath** [comment]
(genuinely curious - I wouldn't have expected that to matter but I don't know ISS well)

**Comment by robynk** [comment]
Without the quotes you get nothing returned, which is also what AI is returning.  In ISS it is quotation marks.  I wondered if it should be brackets in AI because we seem to use them for phrases rather than "

**Comment by robynk** [comment]
I have no idea why it won't work without the quotes.

**Pull request merged**
