### PR TITLE
Avoid checking URL too early after a click

### PR DESCRIPTION
**Pull request by DanielHeath**
We may not have transitioned to the new page yet when we check currentUrl

### CODE REVIEW

**Comment by danni** [comment]
I'm surprised we need this TBH. Since there's an implicit wait in Selenium. What's the use case? It probably needs a comment.

**Comment by DanielHeath** [comment]
So, this 'fixes' it but not for the reasons I had thought (it's basically a `sleep`). 

The underlying problem is that checking the URL doesn't wait for the browser to finish executing JS. As we use history.pushState, a better solution might be to force the use of JS to fetch the URL (since that will add a new event to the browsers queue).

**Comment by DanielHeath** [comment]
++?

**Comment by DanielHeath** [comment]
nvm, this is not ready

**Comment by DanielHeath** [comment]
++?

**Comment by danni** [comment]
++

**Pull request merged**
