### PR TITLE
Visual tests run each platform in travis.yml

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
Consider breaking BROWSERS out into a separate file?

**Comment by DanielHeath** [comment]
Will travis read a separate file?

**Comment by danni** [comment]
Don't know TBH. Yaml can use named nodes, so maybe?

**Comment by DanielHeath** [comment]
I'd be suspicious of a YAML implementation that allowed parsing other files (can I pull in `/etc/passwd`)?

**Comment by DanielHeath** [comment]
I don't see any support for something like that in https://github.com/travis-ci/travis-yaml/blob/master/lib/travis/yaml/parser/psych.rb

**Comment by DanielHeath** [comment]
Any other concerns?

**Comment by danni** [comment]
Okay then. ++

**Pull request merged**
