### PR TITLE
Make back/forwards work like a normal website

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
I reckon this is wrong.

**Comment by DanielHeath** [comment]
The user testers were unanimous about it :/

**Comment by danni** [comment]
Let's run this past @isaacwilliams ?

**Comment by DanielHeath** [comment]
In design meeting with isaac - he's ok to go ahead with this. Good to merge?

**Comment by danni** [comment]
++

**Pull request merged**
