### PR TITLE
Enable config'ing sentry to the amount of transactions sent

### PR DESCRIPTION
**Pull request by callumgare**
https://infoxchange.atlassian.net/browse/AI-321

### CODE REVIEW

**Review by flara-infoxchange — APPROVED** [review]
Looking good

**Review by flara-infoxchange — APPROVED** [review]
++

**Review by flara-infoxchange — APPROVED** [review]
Approve you rusty thing ! Approve !

**Review by flara-infoxchange — APPROVED** [review]
4th time is the charm

**Comment by callumgare** [comment]
> 4th time is the charm

@flara-infoxchange 🎉

**Pull request merged**
