### PR TITLE
Don't try to jscs flowtype interfaces

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
Why?

**Comment by DanielHeath** [comment]
I can't think of a good reason any more. 

I was trying to resolve some flow errors with `if (_.isArray(thing))` not casting `thing` to array inside the if block.

I added an underscore lib definition cribbed from github.com/solnetdigital/flow-interfaces-underscore (which didn't end up helping) but it failed JSCS.

**Comment by danni** [comment]
I think you can just tell jscs to skip one file.

**Comment by DanielHeath** [comment]
Sure, but I also can't think of a good reason to jscs files which don't have any javascript in them.

**Comment by danni** [comment]
Strictly speaking it is JS.

**Comment by DanielHeath** [comment]
I'm not aware of a JS engine that'll use it; babel strips it out before doing anything else.

**Comment by danni** [comment]
No JS engine uses any code style :-P

**Comment by DanielHeath** [comment]
Fair

**Pull request closed without merging**
