### PR TITLE
Prevent attempts to merge generated code

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
++

**Comment by danni** [comment]
Actually I take that back. I think this is wrong because it will overwrite and surprise you. I think the correct thing is to run the script, add that, which will effectively be the merge.

**Comment by danni** [comment]
That way your code won't break by surprise.

**Comment by DanielHeath** [comment]
This just tells git never to attempt a merge (always mark it as a conflict)

**Comment by DanielHeath** [comment]
Separately we could specify a merge strategy (the script)

**Comment by danni** [comment]
Sometimes it will merge fine though.

**Comment by DanielHeath** [comment]
Are you happy for me to add a `.gitstrategies` or similar?

**Comment by DanielHeath** [comment]
This requires git 1.7+ (which is quite old by now).

**Comment by danni** [comment]
++

**Pull request merged**
