### PR TITLE
Upgrade flowtype dependency

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by DanielHeath** [comment]
Flow checks fail on this due to over-aggressive caching in travis (it's running the old version).

**Comment by DanielHeath** [comment]
@kane-c any opinions?

**Comment by kane-c** [comment]
What is needed for the checks to pass in Travis?

**Comment by DanielHeath** [comment]
Travis caches the `node_modules` folder from the master branch (which includes `flow`). 

When I merge it I'll purge the travis caches first, so that the build that follows uses a fresh install (and sets up the cache for future builds).

**Pull request merged**
