### PR TITLE
Fixup: check-shrinkwrap should ignore all dotfiles (eg .DS_Store

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
Is .DS_Store not in your global .gitignore ?

**Comment by danni** [comment]
Or does shrinkwrap not consider that. Should it do that instead?

**Comment by DanielHeath** [comment]
`node_modules` is gitignored - I'm just comparing directory listings to see if you've got deps installed

**Comment by danni** [comment]
++

**Pull request merged**
