### PR TITLE
Load more results button

### PR DESCRIPTION
**Pull request by danni**
A button to load more results.

### CODE REVIEW

**Comment by DanielHeath** [comment]
Looks reasonable. I prefer the async / await style for promise clients but not sure if we've decided to do that everywhere or not.

**Comment by danni** [comment]
@DanielHeath a specific promise? If you're referring to the UI method, that's because it's a UI method and someone needs to resolve the promise (React won't).

**Comment by DanielHeath** [comment]
I was referring to `loadMore` - nothing needs to be bound to the resulting promise (unless I've misunderstood async / await)

**Comment by danni** [comment]
I see, so I can just fire it and it will resolve in the future. Who will handle its exception if it throws one?

**Comment by DanielHeath** [comment]
You'll get a console error but nothing else (much the same as a normal view method)

**Comment by DanielHeath** [comment]
++

**Pull request merged**
