### PR TITLE
Capture screenshots in travis on supported platforms

### PR DESCRIPTION
**Pull request by DanielHeath**
We've been having lots of intermittent bugs that are hard to track down. This should help...

### CODE REVIEW

**Comment by kane-c** [comment]
Are the screenshot files accessible from travis somehow?

How about getting #99 fixed up and merged?

**Comment by DanielHeath** [comment]
This just dumps the base64-encoded screenshot into the build log. Super messy but gets the job done.

**Comment by DanielHeath** [comment]
I'd be ecstatic to get #99 going, but this gets us 70% of the way there for 2 minutes of work.

**Comment by kane-c** [comment]
OK. Do you have an easy-ish way of getting the base64 log into a viewable format?

We did a similar thing here in our GitLab CI logs; Danni wrote a userscript to parse the logs and convert it into an inline image.

**Comment by kane-c** [comment]
:+1:

**Pull request merged**
