### PR TITLE
Visual snapshots

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
Why are we still getting random XML entities in our screenshots?

**Comment by DanielHeath** [comment]
Not just the screenshots - I think webpack is double-escaping something in JSX. 
If you use the server-side render it looks fine on more platforms; the client-side JS doesn't and I haven't looked yet, since we're about to rip out all those icons in favor of the navy design ones which might not have the same issue.

**Comment by danni** [comment]
Let's put in the Navy ones and see if we still have the same problem.

**Comment by DanielHeath** [comment]
Good to merge these in the meantime?

**Comment by danni** [comment]
Also lots of these screenshots still have broken XML attrs in them.

**Pull request merged**
