### PR TITLE
Pre-heat flow server during typecheck to stop flow timing out

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by danni** [comment]
What happens if it hasn't started by the time you're ready for it?

**Comment by DanielHeath** [comment]
Same thing that happens at the moment (`flow` starts the server if its not running, then waits until its up)

**Comment by danni** [comment]
Does this mean I'll have 2 servers?

**Comment by DanielHeath** [comment]
No - it detects theres an existing one and waits for it. They've done a _really_ nice job of it.

**Comment by DanielHeath** [comment]
I've tested this a bunch of different ways - always appears to work well.

**Comment by danni** [comment]
Nice ++

**Pull request merged**
