### PR TITLE
Allow searches to remove service type

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by kane-c** [comment]
Perhaps add a test for this?

**Comment by DanielHeath** [comment]
Done.

**Comment by DanielHeath** [comment]
@kane-c ++?

**Comment by kane-c** [comment]
Why do some search result steps have quotes around the number and others don't?

**Comment by DanielHeath** [comment]
haha, regexp fail (I search-and-replaced and missed some)

**Comment by kane-c** [comment]
:+1:

**Pull request merged**
